files:
  - source: /Lirico/Supporting Files/en.lproj/*.strings
    translation: /Lirico/Supporting Files/%osx_code%/%original_file_name%
  - source: Lirico/en.lproj/*.strings
    translation: /Lirico/%osx_code%/%original_file_name%
