files:
  - source: /Lirico/Supporting Files/Localizable.xcstrings
    translation: /Lirico/Supporting Files/Localizable.xcstrings
    multilingual: true
  - source: /Lirico/Supporting Files/InfoPlist.xcstrings
    translation: /Lirico/Supporting Files/InfoPlist.xcstrings
    multilingual: true
